# Generated by Django 3.0.7 on 2020-07-05 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statuses', '0003_auto_20200705_1835'),
        ('genres', '0002_auto_20200705_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('origin_country', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TvEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('episode_description', models.TextField(blank=True, null=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('still_url', models.CharField(blank=True, max_length=500, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TvUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_date', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('platforms', models.ManyToManyField(blank=True, to='platforms.Platform')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statuses.Priority')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statuses.Status')),
                ('tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.TvEpisode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('original_name', models.CharField(max_length=500)),
                ('show_description', models.TextField(blank=True, null=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('last_air_date', models.DateField(blank=True, null=True)),
                ('poster_url', models.CharField(blank=True, max_length=500, null=True)),
                ('backdrop_url', models.CharField(blank=True, max_length=500, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, to='genres.Genre')),
                ('networks', models.ManyToManyField(blank=True, to='shows.Network')),
            ],
        ),
        migrations.CreateModel(
            name='TvSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('alt_id', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('season_description', models.TextField(blank=True, null=True)),
                ('season_number', models.IntegerField(blank=True, null=True)),
                ('poster_url', models.CharField(blank=True, max_length=500, null=True)),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.TvShow')),
            ],
        ),
        migrations.AddField(
            model_name='tvepisode',
            name='tv_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.TvSeason'),
        ),
    ]
