# Generated by Django 3.0.7 on 2020-07-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name_plural': 'priorities'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
    ]
