# Generated by Django 3.0.7 on 2020-07-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200705_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieuser',
            name='leaving_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
